# Generated by Django 4.1.2 on 2022-11-28 16:21

from django.db import migrations, models
import django.utils.timezone

from core.data_migration.initial_migrations import (
    fill_accounts,
    fill_expense_categories,
    fill_income_categories,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.incomecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('comment', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.expensecategory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('balance__gte', 0)), name='balance__gte__0', violation_error_message='balance must be greater or equal than 0'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(check=models.Q(('count__gt', 0)), name='income__count__gt__0', violation_error_message='count must be greater than 0'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(('count__gt', 0)), name='expense__count__gt__0', violation_error_message='count must be greater than 0'),
        ),

        migrations.RunPython(fill_accounts),
        migrations.RunPython(fill_income_categories),
        migrations.RunPython(fill_expense_categories),
    ]
